name: Backend Tests

on:
  push:
    branches: [ main, Dev/S3, feature/integration-tests, update/profiles]
  pull_request:

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    outputs:
      coverage-file: ${{ steps.coverage-path.outputs.path }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install

      - name: Run unit tests with coverage
        run: npm run test:unit -- --coverageDirectory=coverage/unit
        env:
          EMAILJS_USER_ID: ${{ secrets.EMAILJS_USER_ID }}
          EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
          EMAILJS_INVITATION_TEMPLATE_ID: ${{ secrets.EMAILJS_INVITATION_TEMPLATE_ID }}
          EMAILJS_CONFLICT_TEMPLATE_ID: ${{ secrets.EMAILJS_CONFLICT_TEMPLATE_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

      - name: Save coverage file path
        id: coverage-path
        run: |
          echo "path=coverage/unit/lcov.info" >> $GITHUB_OUTPUT

      - name: Upload unit test artifact
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage
          path: coverage/unit/lcov.info

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

      - name: Run integration tests with coverage
        run: npm run test:integration -- --coverageDirectory=coverage/integration
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          NODE_ENV: test

      - name: Download unit test coverage
        uses: actions/download-artifact@v4
        with:
          name: unit-coverage
          path: coverage/unit

      - name: Merge coverage files
        run: |
          npm install -g lcov-result-merger
          lcov-result-merger "coverage/unit/lcov.info" "coverage/integration/lcov.info" > coverage/merged-lcov.info
          ls -l coverage

      - name: Upload unified coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/merged-lcov.info
          name: codecov-umbrella
